CREATE TABLE category (
    category_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255),
    description VARCHAR(255),
    color       VARCHAR(255)
);

CREATE TABLE task (
    task_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       VARCHAR(255),
    description VARCHAR(255),
    priority    VARCHAR(255),
    status      VARCHAR(255),
    category_id BIGINT REFERENCES category (category_id)
);

CREATE INDEX idx_task_category_id ON task (category_id);
